backend:
  name: github
  repo: physique-chimie-org/physique-chimie-org.github.io
  branch: main

display_url: https://physique-chimie.netlify.app/
publish_mode: editorial_workflow
media_folder: "docs/.vuepress/public/images/uploads"
public_folder: "images/uploads"
collections:
- name: t-spe
  label: "t-spe"
  folder: docs/t-spe
  nested:
      depth: 100 # max depth to show in the collection tree
      summary: "{{title}}"
  identifier_field: title
  extension: md
  widget: "list"
  create: true
  slug: "{{slug}}"
  fields:
    - { name: title, label: Title, widget: string }
    - { name: body, label: Body, widget: markdown }